services:
  docs:
    build:
      context: ..
      dockerfile: docker/Dockerfile.docs
      args:
        user_id: "${UID}"
    working_dir: /home/jenkins
    volumes:
      - ..:/home/jenkins
      - ../.docker_history:/root/.bash_history
    command: /bin/bash
    user: "${UID}:4996"
    tty: true
