name: Build S32k and posix platform

on: [workflow_call, push, pull_request]

jobs:
  run-command:
    runs-on: ubuntu-latest
    strategy:
    #   max-parallel: 1
      matrix:
        preset: [ "tests-posix-debug", "tests-posix-release", "tests-s32k1xx-debug", "tests-s32k1xx-release", "posix-freertos", "posix-threadx", "posix-freertos-with-tracing", "s32k148-freertos-gcc", "s32k148-threadx-gcc", "s32k148-freertos-clang", "s32k148-threadx-clang" ]
        platform: [ "arm", "linux" ]
        config: [ "Debug", "Release", "RelWithDebInfo" ]
        cxxid: ["gcc", "clang"]
        cxxstd: [ 14, 17, 20, 23 ]
        exclude:
          - preset: "tests-posix-debug"
            platform: "arm"
          - preset: "tests-posix-debug"
            config: "Release"
          - preset: "tests-posix-debug"
            config: "RelWithDebInfo"
          - preset: "tests-posix-release"
            platform: "arm"
          - preset: "tests-posix-release"
            config: "Debug"
          - preset: "tests-posix-release"
            config: "RelWithDebInfo"

          - preset: "tests-s32k1xx-debug"
            platform: "arm"
          - preset: "tests-s32k1xx-debug"
            config: "Release"
          - preset: "tests-s32k1xx-debug"
            config: "RelWithDebInfo"
          - preset: "tests-s32k1xx-release"
            platform: "arm"
          - preset: "tests-s32k1xx-release"
            config: "Debug"
          - preset: "tests-s32k1xx-release"
            config: "RelWithDebInfo"

          - preset: "posix-freertos"
            platform: "arm"
          - preset: "posix-threadx"
            platform: "arm"
          - preset: "posix-freertos"
            config: "RelWithDebInfo"
          - preset: "posix-threadx"
            config: "RelWithDebInfo"
          - preset: "posix-freertos-with-tracing"
            platform: "arm"
          - preset: "posix-freertos-with-tracing"
            config: "RelWithDebInfo"

          - preset: "s32k148-freertos-gcc"
            platform: "linux"
          - preset: "s32k148-threadx-gcc"
            platform: "linux"
          - preset: "s32k148-freertos-gcc"
            cxxid: "clang"
          - preset: "s32k148-threadx-gcc"
            cxxid: "clang"

          - preset: "s32k148-freertos-clang"
            platform: "linux"
          - preset: "s32k148-threadx-clang"
            platform: "linux"
          - preset: "s32k148-freertos-clang"
            cxxid: "gcc"
          - preset: "s32k148-threadx-clang"
            cxxid: "gcc"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build development Image
        id: build-docker-development
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:docker/development"
          push: false
          tags: openbsw-development:local
          outputs: type=docker
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Cache CMake files
        id: cache-cmake
        uses: actions/cache@v3
        with:
          path: build
          key: ${{ runner.os }}-${{ steps.build-docker-development.outputs.digest }}-cmake-${{ matrix.preset }}-${{ matrix.config }}-${{ matrix.platform }}-${{ matrix.cxxid }}-${{ matrix.cxxstd }}-${{ hashFiles('**/*.cpp', '**/*.h',  '**/*.cmake', '**/*.txt', '**/*.c', '**/*.s', '**/*.S', '.ci/build.py') }}
          restore-keys: ${{ runner.os }}-${{ steps.build-docker-development.outputs.digest }}-cmake-${{ matrix.preset }}-${{ matrix.config }}-${{ matrix.platform }}-${{ matrix.cxxid }}-${{ matrix.cxxstd }}-

      - name: Run the build.py inside the docker container
        if: steps.cache-cmake.outputs.cache-hit != 'true'
        run: >-
          DOCKER_UID=$(id -u) DOCKER_GID=$(id -g) DOCKER_HISTORY=/dev/null docker compose run --rm development
          python3 .ci/build.py --preset ${{ matrix.preset }} --platform ${{ matrix.platform }} --cxxid ${{ matrix.cxxid }} --cxxstd ${{ matrix.cxxstd }} --config ${{ matrix.config }}

      - name: Run custom CMake build for elf-analyzer
        if: steps.cache-cmake.outputs.cache-hit != 'true' && matrix.platform == 'arm' && matrix.cxxid == 'gcc' && matrix.cxxstd == '14' && matrix.config != ''
        run: >-
          DOCKER_UID=$(id -u) DOCKER_GID=$(id -g) DOCKER_HISTORY=/dev/null docker compose run --rm development
          bash -c "
          cmake --preset ${{ matrix.preset }} -DCMAKE_CXX_FLAGS="-gdwarf-4" -DCMAKE_C_FLAGS="-gdwarf-4" -B elf-analyzer-artifacts/${{ matrix.preset }} &&
          cmake --build elf-analyzer-artifacts/${{ matrix.preset }} -t app.referenceApp --config ${{ matrix.config }}
          "

      - name: Set commit hash and metadata
        if: steps.cache-cmake.outputs.cache-hit != 'true' && matrix.platform == 'arm' && matrix.cxxid == 'gcc' && matrix.cxxstd == '14' && matrix.config != ''
        id: vars
        run: |
          echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "ARTIFACT_NAME=elf-${{ matrix.preset }}-${{ matrix.cxxstd }}-${{ matrix.config }}-gdwarf4-${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Find ELF files
        if: steps.cache-cmake.outputs.cache-hit != 'true' && matrix.platform == 'arm' && matrix.cxxid == 'gcc' && matrix.cxxstd == '14' && matrix.config != ''
        run: |
          mkdir -p elf-artifacts
          cp elf-analyzer-artifacts/${{matrix.preset}}/executables/referenceApp/application/${{ matrix.config }}/app.referenceApp.elf elf-artifacts/

      - name: Upload ELF as GitHub Artifact
        if: steps.cache-cmake.outputs.cache-hit != 'true' && matrix.platform == 'arm'  && matrix.cxxid == 'gcc' && matrix.cxxstd == '14' && matrix.config != ''
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: elf-artifacts/*.elf
