name: Code Coverage

on: [workflow_call, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    env:
      BUILD_TYPE: Debug

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build development Image
        id: build-docker-development
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:docker/development"
          push: false
          tags: openbsw-development:local
          outputs: type=docker
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Cache CMake files
        id: cache-cmake
        uses: actions/cache@v3
        with:
            path: code_coverage
            key: ${{ runner.os }}-${{ steps.build-docker-development.outputs.digest }}-cmake-build-unit-tests-${{ hashFiles('**/*.cpp', '**/*.h',  '**/*.cmake', '**/*.txt', '**/*.c', '**/*.s', '**/*.S', '.ci/code_coverage.py') }}

      - name: Run the code_coverage.py inside the docker container
        if: steps.cache-cmake.outputs.cache-hit != 'true'
        run: >-
          DOCKER_UID=$(id -u) DOCKER_GID=$(id -g) DOCKER_HISTORY=/dev/null docker compose run --rm development
          python3 .ci/code_coverage.py

      - name: Zip code_coverage and coverage_badges
        run: |
              cd code_coverage
              zip -r coverage.zip coverage
              zip -r coverage_badges.zip coverage_badges

      - name: Upload code coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: code_coverage/coverage.zip

      - name: Upload Coverage Badge
        uses: actions/upload-artifact@v4
        with:
          name: coverage_badges
          path: coverage_badges.zip
